[build]
  command = "mv angular.json angular.tmp.json && ng build --configuration production && mv angular.tmp.json angular.json"
  publish = "dist/Portfolio"


[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
