[build]
  command = "powershell -Command \"Rename-Item angular.json angular.tmp\" && ng build --configuration production && powershell -Command \"Rename-Item angular.tmp angular.json\""
  
  publish = "dist/Portfolio"


[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
